server:
  port: 8080
spring:
  application:
    name: Boutique-Hotel-Technikum
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect